server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

---

spring:
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB

---
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sjy?serverTimezone=Asia/Seoul
    username: sjy
    password: 123123

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

---
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 960887353638-t9ins98di8sa1fde8esjdl37fsrsho0h.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          kakao:
            client-id: 1850ead48a3679266e0c4815936bb150
            redirect-uri: http://localhost:8000/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email

          naver:
            client-id: sVKFdPhqa8HmN37O7emS
            client-secret: un3n41AF8R
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
            client-name: Naver
            scope:
              - name
              - email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

